In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst3 = [7,8,9]

In [11]:
arr = np.array([lst1, lst2, lst3])
arr.shape
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Indexing

In [14]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
arr[:,:]
arr[0:2, 0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
arr = np.arange(0,10,3)
arr

array([0, 3, 6, 9])

In [25]:
arr = np.array([1,2,3,4,5,6])
arr[2:] = 400
arr

array([  1,   2, 400, 400, 400, 400])

In [29]:
arr1 = arr.copy()

In [30]:
arr1[2:] = 300
arr

array([  1,   2, 300, 300, 300, 300])

In [35]:
arr = np.ones(4)
arr
something = np.ones((2,5), dtype=int)
something

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])